// Generated by LiveScript 1.2.0
(function(){
  var binders, skelly, ldata, domready, app, client, arr;
  binders = require('../live-binders');
  skelly = require('../');
  ldata = require('../deps/live-data');
  domready = require('domready');
  app = new skelly.App;
  client = skelly.connect(app);
  window.arr = arr = new ldata.Array;
  app.store.set('arr', arr);
  arr.push(new ldata.Value('test'));
  domready(function(){
    return arr.pipe(binders.children(document.body, function(val){
      var el;
      el = document.createElement('div');
      val.pipe(binders.textContent(el));
      return el;
    }));
  });
  window.client = client;
  window.ldata = ldata;
  window.app = app;
}).call(this);
