// Generated by LiveScript 1.2.0
(function(){
  var skelly, server;
  skelly = require('..');
  server = skelly.server({
    'static': __dirname + '/public'
  });
  server.on('client', function(client){
    client.store.on('old_data', function(u){
      return console.log('discarded update:', u);
    });
    return client.rawStore.on('old_data', function(u){
      return console.log('discarded update:', u);
    });
  });
  server.app.store.on('old_data', function(u){
    return console.log('discarded update:', u);
  });
  server.listen(3200);
}).call(this);
