// Generated by LiveScript 1.2.0
(function(){
  var ldata, log, App, exports;
  ldata = require('./live-data');
  log = require('./log');
  App = (function(){
    App.displayName = 'App';
    var prototype = App.prototype, constructor = App;
    function App(opts){
      var ref$;
      this.opts = opts != null
        ? opts
        : {};
      if (!(this instanceof App)) {
        return (function(func, args, ctor) {
          ctor.prototype = func.prototype;
          var child = new ctor, result = func.apply(child, args), t;
          return (t = typeof result)  == "object" || t == "function" ? result || child : child;
  })(App, arguments, function(){});
      }
      (ref$ = this.opts).logger == null && (ref$.logger = log.logger({
        level: 'debug'
      }));
      this.log = this.opts.logger;
      this.store = new ldata.Map({
        prefix: 'app'
      });
    }
    return App;
  }());
  exports = module.exports = App;
}).call(this);
