// Generated by LiveScript 1.2.0
(function(){
  var View;
  View = (function(){
    View.displayName = 'View';
    var prototype = View.prototype, constructor = View;
    function View(){}
    return View;
  }());
  module.exports = View;
}).call(this);
