// Generated by LiveScript 1.2.0
(function(){
  var skelly, server;
  skelly = require('skelly');
  server = skell.server({
    'static': __dirname + "/public"
  });
  server.listen(3000);
}).call(this);
